name: Fossology
on:
  workflow_dispatch: {}
  push:
   branches:
     - fossology

jobs:
  license_check_job: 
    name: license_check
    runs-on: ubuntu-18.04
    container: fossology/fossology:scanner
    steps: 
     - name: SCS TypeScript SDK  Checkout
       uses: actions/checkout@v1
# license_check
     - name: license checking 
       run: /bin/fossologyscanner nomos ojo
# Archive artifact
     - name: Archive TypeScript Package
       uses: actions/upload-artifact@v2
       with:
         name: license_check
         path: |
            - results

  copyright_check:
    name: CopyRights_check
    runs-on: ubuntu-18.04
    container: fossology/fossology:scanner
    steps: 
     - name: SCS TypeScript SDK  Checkout
       uses: actions/checkout@v1
# Copy_Right_Check
     - name: Copy_Rights_checking 
       run: /bin/fossologyscanner copyright keyword
# Archive Artifact
     - name: Archive TypeScript Package
       uses: actions/upload-artifact@v2
       with:
         name: Copy_Rights_check
         path: |
            - results
