name: Fossology
on:
  workflow_dispatch: {}
  push:
   branches:
     - fossology

jobs:
  license_check_job: 
    name: license_check
    runs-on: ubuntu-18.04
    steps: 
     - name: SCS TypeScript SDK  Checkout
       uses: actions/checkout@v2
     # license checking
     
     - name: Check License Lines
       uses: kt3k/license_checker@v1.0.6
       
