name: Fossology
on:
  workflow_dispatch: {}
  push:
   branches:
     - fossology

jobs:
  license_check_job: 
    name: license_check
    runs-on: ubuntu-18.04
    steps: 
     - name: SCS TypeScript SDK  Checkout
       uses: actions/checkout@v1
# docker setup 
     - name: setup docker buildX
       uses:  docker/setup-buildx-action@v1
# license_check
     - name: license checking 
       run: pwd
       #run: docker run --rm -v ./:/project fossology/atarashi:latest -a DLD -l report_license_check.csv /project/andriod
# Archive artifact
     - name: Archive TypeScript Package
       uses: actions/upload-artifact@v2
       with:
         name: license_check
         path: |
            - project/report_license_check.csv

  copyright_check:
    name: CopyRights_check
    runs-on: ubuntu-18.04
    steps: 
     - name: SCS TypeScript SDK  Checkout
       uses: actions/checkout@v1
# Copy_Right_Check
     - name: Copy_Rights_checking 
       run: docker run --rm -v ./:/project fossology/atarashi:latest -a DLD -l report_copy_right.csv /project/android
# Archive Artifact
     - name: Archive TypeScript Package
       uses: actions/upload-artifact@v2
       with:
         name: Copy_Rights_check
         path: |
            - project/report_copy_right.csv
